export interface ElementData {
  name: string;
  symbol: string;
  atomicNumber: number;
  atomicMass: number;
  group: string;
  period: number;
  block: string;
  metalNonmetal: string;
  phase: string;
  color: string;
  density: string;
  meltingPoint: string;
  boilingPoint: string;
  electronConfiguration: string;
  electronegativity: string;
  ionizationEnergy: string;
  bonding: string;
  position: number;
  category?: string;
}

export const elements: ElementData[] = [
  {
    name: "Hidrojen",
    symbol: "H",
    atomicNumber: 1,
    atomicMass: 1.008,
    group: "1A",
    period: 1,
    block: "s",
    metalNonmetal: "Ametal",
    phase: "Gaz",
    color: "Renksiz",
    density: "0.08988 g/L",
    meltingPoint: "-259.16 °C",
    boilingPoint: "-252.87 °C",
    electronConfiguration: "1s¹",
    electronegativity: "2.20",
    ionizationEnergy: "1312 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar, iyonik bağlar da oluşturabilir.",
    position: 1,
    category: "alkali metal", // Hidrojen özel bir durum, ancak alkali metal olarak kabul edilebilir
  },
  {
    name: "Helyum",
    symbol: "He",
    atomicNumber: 2,
    atomicMass: 4.0026,
    group: "8A",
    period: 1,
    block: "s",
    metalNonmetal: "Ametal",
    phase: "Gaz",
    color: "Renksiz",
    density: "0.1786 g/L",
    meltingPoint: "-272.2 °C",
    boilingPoint: "-268.93 °C",
    electronConfiguration: "1s²",
    electronegativity: "Yok (soygaz olduğu için)",
    ionizationEnergy: "2372 kJ/mol",
    bonding: "İnert, kimyasal bağ oluşturmaz.",
    position: 18,
    category: "soygaz",
  },
  {
    name: "Lityum",
    symbol: "Li",
    atomicNumber: 3,
    atomicMass: 6.94,
    group: "1A",
    period: 2,
    block: "s",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "0.534 g/cm³",
    meltingPoint: "180.54 °C",
    boilingPoint: "1342 °C",
    electronConfiguration: "[He] 2s¹",
    electronegativity: "0.98",
    ionizationEnergy: "520 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 1,
    category: "alkali metal",
  },
  {
    name: "Berilyum",
    symbol: "Be",
    atomicNumber: 4,
    atomicMass: 9.0122,
    group: "2A",
    period: 2,
    block: "s",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gri",
    density: "1.848 g/cm³",
    meltingPoint: "1287 °C",
    boilingPoint: "2469 °C",
    electronConfiguration: "[He] 2s²",
    electronegativity: "1.57",
    ionizationEnergy: "899 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 2,
    category: "toprak alkali metal",
  },
  {
    name: "Bor",
    symbol: "B",
    atomicNumber: 5,
    atomicMass: 10.81,
    group: "3A",
    period: 2,
    block: "p",
    metalNonmetal: "Yarı metal",
    phase: "Katı",
    color: "Siyah",
    density: "2.34 g/cm³",
    meltingPoint: "2075 °C",
    boilingPoint: "4000 °C",
    electronConfiguration: "[He] 2s² 2p¹",
    electronegativity: "2.04",
    ionizationEnergy: "800.6 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 13,
    category: "bor grubu",
  },
  {
    name: "Karbon",
    symbol: "C",
    atomicNumber: 6,
    atomicMass: 12.011,
    group: "4A",
    period: 2,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Katı",
    color: "Siyah (grafit) veya renksiz (elmas)",
    density: "2.267 g/cm³ (grafit); 3.515 g/cm³ (elmas)",
    meltingPoint: "3550 °C",
    boilingPoint: "4027 °C",
    electronConfiguration: "[He] 2s² 2p²",
    electronegativity: "2.55",
    ionizationEnergy: "1086.5 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 14,
    category: "karbon grubu",
  },
  {
    name: "Azot",
    symbol: "N",
    atomicNumber: 7,
    atomicMass: 14.007,
    group: "5A",
    period: 2,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Gaz",
    color: "Renksiz",
    density: "1.2506 g/L",
    meltingPoint: "-210 °C",
    boilingPoint: "-195.79 °C",
    electronConfiguration: "[He] 2s² 2p³",
    electronegativity: "3.04",
    ionizationEnergy: "1402.3 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 15,
    category: "azot grubu",
  },
  {
    name: "Oksijen",
    symbol: "O",
    atomicNumber: 8,
    atomicMass: 15.999,
    group: "6A",
    period: 2,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Gaz",
    color: "Renksiz",
    density: "1.429 g/L",
    meltingPoint: "-218.79 °C",
    boilingPoint: "-182.95 °C",
    electronConfiguration: "[He] 2s² 2p⁴",
    electronegativity: "3.44",
    ionizationEnergy: "1313.9 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 16,
    category: "kalkojen",
  },
  {
    name: "Flor",
    symbol: "F",
    atomicNumber: 9,
    atomicMass: 18.998,
    group: "7A",
    period: 2,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Gaz",
    color: "Soluk sarı",
    density: "1.696 g/L",
    meltingPoint: "-219.67 °C",
    boilingPoint: "-188.11 °C",
    electronConfiguration: "[He] 2s² 2p⁵",
    electronegativity: "3.98",
    ionizationEnergy: "1681 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 17,
    category: "halojen",
  },
  {
    name: "Neon",
    symbol: "Ne",
    atomicNumber: 10,
    atomicMass: 20.18,
    group: "8A",
    period: 2,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Gaz",
    color: "Renksiz",
    density: "0.9002 g/L",
    meltingPoint: "-248.59 °C",
    boilingPoint: "-246.08 °C",
    electronConfiguration: "[He] 2s² 2p⁶",
    electronegativity: "Yok (soygaz olduğu için)",
    ionizationEnergy: "2080.7 kJ/mol",
    bonding: "Kimyasal bağ yapmaz.",
    position: 18,
    category: "soygaz",
  },
  {
    name: "Sodyum",
    symbol: "Na",
    atomicNumber: 11,
    atomicMass: 22.99,
    group: "1A",
    period: 3,
    block: "s",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş beyazı",
    density: "0.971 g/cm³",
    meltingPoint: "97.72 °C",
    boilingPoint: "883 °C",
    electronConfiguration: "[Ne] 3s¹",
    electronegativity: "0.93",
    ionizationEnergy: "495.8 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 1,
    category: "alkali metal",
  },
  {
    name: "Magnezyum",
    symbol: "Mg",
    atomicNumber: 12,
    atomicMass: 24.305,
    group: "2A",
    period: 3,
    block: "s",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş beyazı",
    density: "1.738 g/cm³",
    meltingPoint: "650 °C",
    boilingPoint: "1090 °C",
    electronConfiguration: "[Ne] 3s²",
    electronegativity: "1.31",
    ionizationEnergy: "737.7 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 2,
    category: "toprak alkali metal",
  },
  {
    name: "Alüminyum",
    symbol: "Al",
    atomicNumber: 13,
    atomicMass: 26.982,
    group: "3A",
    period: 3,
    block: "p",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş beyazı",
    density: "2.70 g/cm³",
    meltingPoint: "660.32 °C",
    boilingPoint: "2470 °C",
    electronConfiguration: "[Ne] 3s² 3p¹",
    electronegativity: "1.61",
    ionizationEnergy: "577.5 kJ/mol",
    bonding:
      "Genellikle iyonik bağ yapar, ancak bazı bileşiklerde kovalent bağ da yapabilir.",
    position: 13,
    category: "bor grubu",
  },
  {
    name: "Silisyum",
    symbol: "Si",
    atomicNumber: 14,
    atomicMass: 28.085,
    group: "4A",
    period: 3,
    block: "p",
    metalNonmetal: "Yarı metal",
    phase: "Katı",
    color: "Gri",
    density: "2.329 g/cm³",
    meltingPoint: "1414 °C",
    boilingPoint: "3265 °C",
    electronConfiguration: "[Ne] 3s² 3p²",
    electronegativity: "1.90",
    ionizationEnergy: "786.5 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 14,
    category: "karbon grubu",
  },
  {
    name: "Fosfor",
    symbol: "P",
    atomicNumber: 15,
    atomicMass: 30.974,
    group: "5A",
    period: 3,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Katı",
    color: "Beyaz (beyaz fosfor) veya kırmızı",
    density: "1.82 g/cm³ (beyaz fosfor)",
    meltingPoint: "44.15 °C (beyaz fosfor)",
    boilingPoint: "280 °C",
    electronConfiguration: "[Ne] 3s² 3p³",
    electronegativity: "2.19",
    ionizationEnergy: "1011.8 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 15,
    category: "azot grubu",
  },
  {
    name: "Kükürt",
    symbol: "S",
    atomicNumber: 16,
    atomicMass: 32.06,
    group: "6A",
    period: 3,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Katı",
    color: "Sarı",
    density: "2.067 g/cm³",
    meltingPoint: "115.21 °C",
    boilingPoint: "444.6 °C",
    electronConfiguration: "[Ne] 3s² 3p⁴",
    electronegativity: "2.58",
    ionizationEnergy: "999.6 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 16,
    category: "kalkojen",
  },
  {
    name: "Klor",
    symbol: "Cl",
    atomicNumber: 17,
    atomicMass: 35.45,
    group: "7A",
    period: 3,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Gaz",
    color: "Sarı-yeşil",
    density: "3.214 g/L",
    meltingPoint: "-101.5 °C",
    boilingPoint: "-34.04 °C",
    electronConfiguration: "[Ne] 3s² 3p⁵",
    electronegativity: "3.16",
    ionizationEnergy: "1251.2 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 17,
    category: "halojen",
  },
  {
    name: "Argon",
    symbol: "Ar",
    atomicNumber: 18,
    atomicMass: 39.948,
    group: "8A",
    period: 3,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Gaz",
    color: "Renksiz",
    density: "1.784 g/L",
    meltingPoint: "-189.34 °C",
    boilingPoint: "-185.85 °C",
    electronConfiguration: "[Ne] 3s² 3p⁶",
    electronegativity: "Yok (soygaz olduğu için)",
    ionizationEnergy: "1520.6 kJ/mol",
    bonding: "Kimyasal bağ yapmaz.",
    position: 18,
    category: "soygaz",
  },
  {
    name: "Potasyum",
    symbol: "K",
    atomicNumber: 19,
    atomicMass: 39.098,
    group: "1A",
    period: 4,
    block: "s",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş beyazı",
    density: "0.856 g/cm³",
    meltingPoint: "63.5 °C",
    boilingPoint: "759 °C",
    electronConfiguration: "[Ar] 4s¹",
    electronegativity: "0.82",
    ionizationEnergy: "418.8 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 1,
    category: "alkali metal",
  },
  {
    name: "Kalsiyum",
    symbol: "Ca",
    atomicNumber: 20,
    atomicMass: 40.078,
    group: "2A",
    period: 4,
    block: "s",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş beyazı",
    density: "1.54 g/cm³",
    meltingPoint: "842 °C",
    boilingPoint: "1484 °C",
    electronConfiguration: "[Ar] 4s²",
    electronegativity: "1.00",
    ionizationEnergy: "589.8 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 2,
    category: "toprak alkali metal",
  },
  {
    name: "Skandiyum",
    symbol: "Sc",
    atomicNumber: 21,
    atomicMass: 44.955,
    group: "3B",
    period: 4,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş beyazı",
    density: "2.985 g/cm³",
    meltingPoint: "1541 °C",
    boilingPoint: "2836 °C",
    electronConfiguration: "[Ar] 3d¹ 4s²",
    electronegativity: "1.36",
    ionizationEnergy: "633.1 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 3,
    category: "geçiş metali", // Geçiş metalleri için özel kategori
  },
  {
    name: "Titanyum",
    symbol: "Ti",
    atomicNumber: 22,
    atomicMass: 47.867,
    group: "4B",
    period: 4,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "4.506 g/cm³",
    meltingPoint: "1668 °C",
    boilingPoint: "3287 °C",
    electronConfiguration: "[Ar] 3d² 4s²",
    electronegativity: "1.54",
    ionizationEnergy: "658.8 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 4,
    category: "geçiş metali",
  },
  {
    name: "Vanadyum",
    symbol: "V",
    atomicNumber: 23,
    atomicMass: 50.942,
    group: "5B",
    period: 4,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş gri",
    density: "6.11 g/cm³",
    meltingPoint: "1910 °C",
    boilingPoint: "3407 °C",
    electronConfiguration: "[Ar] 3d³ 4s²",
    electronegativity: "1.63",
    ionizationEnergy: "650.9 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 5,
    category: "geçiş metali",
  },
  {
    name: "Krom",
    symbol: "Cr",
    atomicNumber: 24,
    atomicMass: 51.996,
    group: "6B",
    period: 4,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "7.15 g/cm³",
    meltingPoint: "1907 °C",
    boilingPoint: "2671 °C",
    electronConfiguration: "[Ar] 3d⁵ 4s¹",
    electronegativity: "1.66",
    ionizationEnergy: "652.9 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 6,
    category: "geçiş metali",
  },
  {
    name: "Manganez",
    symbol: "Mn",
    atomicNumber: 25,
    atomicMass: 54.938,
    group: "7B",
    period: 4,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "7.44 g/cm³",
    meltingPoint: "1246 °C",
    boilingPoint: "2061 °C",
    electronConfiguration: "[Ar] 3d⁵ 4s²",
    electronegativity: "1.55",
    ionizationEnergy: "717.3 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 7,
    category: "geçiş metali",
  },
  {
    name: "Demir",
    symbol: "Fe",
    atomicNumber: 26,
    atomicMass: 55.845,
    group: "8B",
    period: 4,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş gri",
    density: "7.874 g/cm³",
    meltingPoint: "1538 °C",
    boilingPoint: "2862 °C",
    electronConfiguration: "[Ar] 3d⁶ 4s²",
    electronegativity: "1.83",
    ionizationEnergy: "762.5 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 8,
    category: "geçiş metali",
  },
  {
    name: "Kobalt",
    symbol: "Co",
    atomicNumber: 27,
    atomicMass: 58.933,
    group: "8B",
    period: 4,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "8.86 g/cm³",
    meltingPoint: "1495 °C",
    boilingPoint: "2927 °C",
    electronConfiguration: "[Ar] 3d⁷ 4s²",
    electronegativity: "1.88",
    ionizationEnergy: "760.4 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 9,
    category: "geçiş metali",
  },
  {
    name: "Nikel",
    symbol: "Ni",
    atomicNumber: 28,
    atomicMass: 58.693,
    group: "8B",
    period: 4,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "8.912 g/cm³",
    meltingPoint: "1455 °C",
    boilingPoint: "2913 °C",
    electronConfiguration: "[Ar] 3d⁸ 4s²",
    electronegativity: "1.91",
    ionizationEnergy: "737.1 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 10,
    category: "geçiş metali",
  },
  {
    name: "Bakır",
    symbol: "Cu",
    atomicNumber: 29,
    atomicMass: 63.546,
    group: "1B",
    period: 4,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Kırmızımsı",
    density: "8.96 g/cm³",
    meltingPoint: "1084.62 °C",
    boilingPoint: "2562 °C",
    electronConfiguration: "[Ar] 3d¹⁰ 4s¹",
    electronegativity: "1.90",
    ionizationEnergy: "745.5 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 11,
    category: "geçiş metali",
  },
  {
    name: "Çinko",
    symbol: "Zn",
    atomicNumber: 30,
    atomicMass: 65.38,
    group: "2B",
    period: 4,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "7.14 g/cm³",
    meltingPoint: "419.53 °C",
    boilingPoint: "907 °C",
    electronConfiguration: "[Ar] 3d¹⁰ 4s²",
    electronegativity: "1.65",
    ionizationEnergy: "906.4 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 12,
    category: "geçiş metali",
  },
  {
    name: "Galyum",
    symbol: "Ga",
    atomicNumber: 31,
    atomicMass: 69.723,
    group: "3A",
    period: 4,
    block: "p",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "5.91 g/cm³",
    meltingPoint: "29.76 °C",
    boilingPoint: "2204 °C",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p¹",
    electronegativity: "1.81",
    ionizationEnergy: "578.8 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 13,
    category: "bor grubu",
  },
  {
    name: "Germanyum",
    symbol: "Ge",
    atomicNumber: 32,
    atomicMass: 72.63,
    group: "4A",
    period: 4,
    block: "p",
    metalNonmetal: "Yarı metal",
    phase: "Katı",
    color: "Gri beyaz",
    density: "5.323 g/cm³",
    meltingPoint: "938.25 °C",
    boilingPoint: "2833 °C",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p²",
    electronegativity: "2.01",
    ionizationEnergy: "762 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 14,
    category: "karbon grubu",
  },
  {
    name: "Arsenik",
    symbol: "As",
    atomicNumber: 33,
    atomicMass: 74.922,
    group: "5A",
    period: 4,
    block: "p",
    metalNonmetal: "Yarı metal",
    phase: "Katı",
    color: "Gri",
    density: "5.776 g/cm³",
    meltingPoint: "817 °C",
    boilingPoint: "614 °C (süblimleşir)",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p³",
    electronegativity: "2.18",
    ionizationEnergy: "947 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 15,
    category: "azot grubu",
  },
  {
    name: "Selenyum",
    symbol: "Se",
    atomicNumber: 34,
    atomicMass: 78.971,
    group: "6A",
    period: 4,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Katı",
    color: "Gri",
    density: "4.81 g/cm³",
    meltingPoint: "221 °C",
    boilingPoint: "685 °C",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁴",
    electronegativity: "2.55",
    ionizationEnergy: "941 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 16,
    category: "kalkojen",
  },
  {
    name: "Brom",
    symbol: "Br",
    atomicNumber: 35,
    atomicMass: 79.904,
    group: "7A",
    period: 4,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Sıvı",
    color: "Kırmızımsı kahverengi",
    density: "3.1028 g/cm³",
    meltingPoint: "-7.2 °C",
    boilingPoint: "58.8 °C",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁵",
    electronegativity: "2.96",
    ionizationEnergy: "1139.9 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 17,
    category: "halojen",
  },
  {
    name: "Kripton",
    symbol: "Kr",
    atomicNumber: 36,
    atomicMass: 83.798,
    group: "8A",
    period: 4,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Gaz",
    color: "Renksiz",
    density: "3.749 g/L",
    meltingPoint: "-157.36 °C",
    boilingPoint: "-153.22 °C",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁶",
    electronegativity: "Yok (soygaz olduğu için)",
    ionizationEnergy: "1350.8 kJ/mol",
    bonding: "Kimyasal bağ yapmaz.",
    position: 18,
    category: "soygaz",
  },
  {
    name: "Rubidyum",
    symbol: "Rb",
    atomicNumber: 37,
    atomicMass: 85.468,
    group: "1A",
    period: 5,
    block: "s",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş beyazı",
    density: "1.532 g/cm³",
    meltingPoint: "39.31 °C",
    boilingPoint: "688 °C",
    electronConfiguration: "[Kr] 5s¹",
    electronegativity: "0.82",
    ionizationEnergy: "403 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 1,
    category: "alkali metal",
  },
  {
    name: "Stronsiyum",
    symbol: "Sr",
    atomicNumber: 38,
    atomicMass: 87.62,
    group: "2A",
    period: 5,
    block: "s",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş beyazı",
    density: "2.64 g/cm³",
    meltingPoint: "777 °C",
    boilingPoint: "1382 °C",
    electronConfiguration: "[Kr] 5s²",
    electronegativity: "0.95",
    ionizationEnergy: "549.5 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 2,
    category: "toprak alkali metal",
  },
  {
    name: "İtriyum",
    symbol: "Y",
    atomicNumber: 39,
    atomicMass: 88.906,
    group: "3B",
    period: 5,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "4.472 g/cm³",
    meltingPoint: "1526 °C",
    boilingPoint: "3338 °C",
    electronConfiguration: "[Kr] 4d¹ 5s²",
    electronegativity: "1.22",
    ionizationEnergy: "600 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 3,
    category: "geçiş metali",
  },
  {
    name: "Zirkonyum",
    symbol: "Zr",
    atomicNumber: 40,
    atomicMass: 91.224,
    group: "4B",
    period: 5,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "6.52 g/cm³",
    meltingPoint: "1855 °C",
    boilingPoint: "4409 °C",
    electronConfiguration: "[Kr] 4d² 5s²",
    electronegativity: "1.33",
    ionizationEnergy: "640.1 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 4,
    category: "geçiş metali",
  },
  {
    name: "Niobyum",
    symbol: "Nb",
    atomicNumber: 41,
    atomicMass: 92.906,
    group: "5B",
    period: 5,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "8.57 g/cm³",
    meltingPoint: "2477 °C",
    boilingPoint: "4744 °C",
    electronConfiguration: "[Kr] 4d⁴ 5s¹",
    electronegativity: "1.6",
    ionizationEnergy: "652.1 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 5,
    category: "geçiş metali",
  },
  {
    name: "Molibden",
    symbol: "Mo",
    atomicNumber: 42,
    atomicMass: 95.95,
    group: "6B",
    period: 5,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "10.22 g/cm³",
    meltingPoint: "2623 °C",
    boilingPoint: "4639 °C",
    electronConfiguration: "[Kr] 4d⁵ 5s¹",
    electronegativity: "2.16",
    ionizationEnergy: "684.3 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 6,
    category: "geçiş metali",
  },
  {
    name: "Teknesyum",
    symbol: "Tc",
    atomicNumber: 43,
    atomicMass: 98,
    group: "7B",
    period: 5,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "11 g/cm³",
    meltingPoint: "2157 °C",
    boilingPoint: "4265 °C",
    electronConfiguration: "[Kr] 4d⁵ 5s²",
    electronegativity: "1.9",
    ionizationEnergy: "702 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 7,
  },
  {
    name: "Rutenyum",
    symbol: "Ru",
    atomicNumber: 44,
    atomicMass: 101.07,
    group: "8B",
    period: 5,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "12.1 g/cm³",
    meltingPoint: "2334 °C",
    boilingPoint: "4150 °C",
    electronConfiguration: "[Kr] 4d⁷ 5s¹",
    electronegativity: "2.2",
    ionizationEnergy: "710.2 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 8,
  },
  {
    name: "Rodyum",
    symbol: "Rh",
    atomicNumber: 45,
    atomicMass: 102.91,
    group: "8B",
    period: 5,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "12.41 g/cm³",
    meltingPoint: "1964 °C",
    boilingPoint: "3695 °C",
    electronConfiguration: "[Kr] 4d⁸ 5s¹",
    electronegativity: "2.28",
    ionizationEnergy: "719.7 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 9,
  },
  {
    name: "Paladyum",
    symbol: "Pd",
    atomicNumber: 46,
    atomicMass: 106.42,
    group: "8B",
    period: 5,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "12.02 g/cm³",
    meltingPoint: "1554.9 °C",
    boilingPoint: "2963 °C",
    electronConfiguration: "[Kr] 4d¹⁰",
    electronegativity: "2.20",
    ionizationEnergy: "804.4 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 10,
  },
  {
    name: "Gümüş",
    symbol: "Ag",
    atomicNumber: 47,
    atomicMass: 107.87,
    group: "1B",
    period: 5,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "10.49 g/cm³",
    meltingPoint: "961.78 °C",
    boilingPoint: "2162 °C",
    electronConfiguration: "[Kr] 4d¹⁰ 5s¹",
    electronegativity: "1.93",
    ionizationEnergy: "731.0 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 11,
  },
  {
    name: "Kadmiyum",
    symbol: "Cd",
    atomicNumber: 48,
    atomicMass: 112.41,
    group: "2B",
    period: 5,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "8.65 g/cm³",
    meltingPoint: "321.07 °C",
    boilingPoint: "767 °C",
    electronConfiguration: "[Kr] 4d¹⁰ 5s²",
    electronegativity: "1.69",
    ionizationEnergy: "867.8 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 12,
  },
  {
    name: "İndiyum",
    symbol: "In",
    atomicNumber: 49,
    atomicMass: 114.82,
    group: "3A",
    period: 5,
    block: "p",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "7.31 g/cm³",
    meltingPoint: "156.60 °C",
    boilingPoint: "2072 °C",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p¹",
    electronegativity: "1.78",
    ionizationEnergy: "558.3 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 13,
  },
  {
    name: "Kalay",
    symbol: "Sn",
    atomicNumber: 50,
    atomicMass: 118.71,
    group: "4A",
    period: 5,
    block: "p",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "7.287 g/cm³",
    meltingPoint: "231.93 °C",
    boilingPoint: "2602 °C",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p²",
    electronegativity: "1.96",
    ionizationEnergy: "708.6 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 14,
  },
  {
    name: "Antimon",
    symbol: "Sb",
    atomicNumber: 51,
    atomicMass: 121.76,
    group: "5A",
    period: 5,
    block: "p",
    metalNonmetal: "Yarı metal",
    phase: "Katı",
    color: "Gümüş",
    density: "6.685 g/cm³",
    meltingPoint: "630.63 °C",
    boilingPoint: "1587 °C",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p³",
    electronegativity: "2.05",
    ionizationEnergy: "834.0 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 15,
  },
  {
    name: "Tellür",
    symbol: "Te",
    atomicNumber: 52,
    atomicMass: 127.6,
    group: "6A",
    period: 5,
    block: "p",
    metalNonmetal: "Yarı metal",
    phase: "Katı",
    color: "Gümüş",
    density: "6.24 g/cm³",
    meltingPoint: "449.51 °C",
    boilingPoint: "988 °C",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁴",
    electronegativity: "2.1",
    ionizationEnergy: "869.3 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 16,
  },
  {
    name: "İyot",
    symbol: "I",
    atomicNumber: 53,
    atomicMass: 126.9,
    group: "7A",
    period: 5,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Katı",
    color: "Mor",
    density: "4.93 g/cm³",
    meltingPoint: "113.7 °C",
    boilingPoint: "184.3 °C",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁵",
    electronegativity: "2.66",
    ionizationEnergy: "1008.4 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 17,
  },
  {
    name: "Ksenon",
    symbol: "Xe",
    atomicNumber: 54,
    atomicMass: 131.29,
    group: "8A",
    period: 5,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Gaz",
    color: "Renksiz",
    density: "5.894 g/L",
    meltingPoint: "-111.8 °C",
    boilingPoint: "-108.1 °C",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁶",
    electronegativity: "Yok (soygaz olduğu için)",
    ionizationEnergy: "1170.4 kJ/mol",
    bonding: "Kimyasal bağ yapmaz.",
    position: 18,
  },
  {
    name: "Sezyum",
    symbol: "Cs",
    atomicNumber: 55,
    atomicMass: 132.91,
    group: "1A",
    period: 6,
    block: "s",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Altın",
    density: "1.93 g/cm³",
    meltingPoint: "28.44 °C",
    boilingPoint: "671 °C",
    electronConfiguration: "[Xe] 6s¹",
    electronegativity: "0.79",
    ionizationEnergy: "375.7 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 1,
  },
  {
    name: "Baryum",
    symbol: "Ba",
    atomicNumber: 56,
    atomicMass: 137.33,
    group: "2A",
    period: 6,
    block: "s",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "3.62 g/cm³",
    meltingPoint: "727 °C",
    boilingPoint: "1845 °C",
    electronConfiguration: "[Xe] 6s²",
    electronegativity: "0.89",
    ionizationEnergy: "502.9 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 2,
  },
  {
    name: "Lantan",
    symbol: "La",
    atomicNumber: 57,
    atomicMass: 138.91,
    group: "3B",
    period: 6,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "6.15 g/cm³",
    meltingPoint: "920 °C",
    boilingPoint: "3464 °C",
    electronConfiguration: "[Xe] 5d¹ 6s²",
    electronegativity: "1.10",
    ionizationEnergy: "538.1 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 3,
  },
  {
    name: "Seryum",
    symbol: "Ce",
    atomicNumber: 58,
    atomicMass: 140.12,
    group: "3B",
    period: 6,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "6.77 g/cm³",
    meltingPoint: "798 °C",
    boilingPoint: "3443 °C",
    electronConfiguration: "[Xe] 4f¹ 5d¹ 6s²",
    electronegativity: "1.12",
    ionizationEnergy: "534.4 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 4,
  },
  {
    name: "Praseodim",
    symbol: "Pr",
    atomicNumber: 59,
    atomicMass: 140.91,
    group: "3B",
    period: 6,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "6.77 g/cm³",
    meltingPoint: "931 °C",
    boilingPoint: "3520 °C",
    electronConfiguration: "[Xe] 4f³ 6s²",
    electronegativity: "1.13",
    ionizationEnergy: "527 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 5,
  },
  {
    name: "Neodim",
    symbol: "Nd",
    atomicNumber: 60,
    atomicMass: 144.24,
    group: "3B",
    period: 6,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "7.01 g/cm³",
    meltingPoint: "1024 °C",
    boilingPoint: "3074 °C",
    electronConfiguration: "[Xe] 4f⁴ 6s²",
    electronegativity: "1.14",
    ionizationEnergy: "533.1 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 6,
  },
  {
    name: "Prometyum",
    symbol: "Pm",
    atomicNumber: 61,
    atomicMass: 145,
    group: "3B",
    period: 6,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "7.26 g/cm³",
    meltingPoint: "1100 °C",
    boilingPoint: "3000 °C",
    electronConfiguration: "[Xe] 4f⁵ 6s²",
    electronegativity: "1.13",
    ionizationEnergy: "540 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 7,
  },
  {
    name: "Samaryum",
    symbol: "Sm",
    atomicNumber: 62,
    atomicMass: 150.36,
    group: "3B",
    period: 6,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "7.52 g/cm³",
    meltingPoint: "1072 °C",
    boilingPoint: "1900 °C",
    electronConfiguration: "[Xe] 4f⁶ 6s²",
    electronegativity: "1.17",
    ionizationEnergy: "544.5 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 8,
  },
  {
    name: "Evropiyum",
    symbol: "Eu",
    atomicNumber: 63,
    atomicMass: 151.96,
    group: "3B",
    period: 6,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "5.24 g/cm³",
    meltingPoint: "822 °C",
    boilingPoint: "1597 °C",
    electronConfiguration: "[Xe] 4f⁷ 6s²",
    electronegativity: "1.2",
    ionizationEnergy: "547.1 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 9,
  },
  {
    name: "Gadolinyum",
    symbol: "Gd",
    atomicNumber: 64,
    atomicMass: 157.25,
    group: "3B",
    period: 6,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "7.90 g/cm³",
    meltingPoint: "1312 °C",
    boilingPoint: "3273 °C",
    electronConfiguration: "[Xe] 4f⁷ 5d¹ 6s²",
    electronegativity: "1.2",
    ionizationEnergy: "593.4 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 10,
  },
  {
    name: "Terbiyum",
    symbol: "Tb",
    atomicNumber: 65,
    atomicMass: 158.93,
    group: "3B",
    period: 6,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "8.23 g/cm³",
    meltingPoint: "1356 °C",
    boilingPoint: "3230 °C",
    electronConfiguration: "[Xe] 4f⁹ 6s²",
    electronegativity: "1.2",
    ionizationEnergy: "565.8 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 11,
  },
  {
    name: "Disprosyum",
    symbol: "Dy",
    atomicNumber: 66,
    atomicMass: 162.5,
    group: "3B",
    period: 6,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "8.55 g/cm³",
    meltingPoint: "1412 °C",
    boilingPoint: "2562 °C",
    electronConfiguration: "[Xe] 4f¹⁰ 6s²",
    electronegativity: "1.22",
    ionizationEnergy: "573.0 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 12,
  },
  {
    name: "Holmiyum",
    symbol: "Ho",
    atomicNumber: 67,
    atomicMass: 164.93,
    group: "3B",
    period: 6,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "8.80 g/cm³",
    meltingPoint: "1474 °C",
    boilingPoint: "2700 °C",
    electronConfiguration: "[Xe] 4f¹¹ 6s²",
    electronegativity: "1.23",
    ionizationEnergy: "581.0 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 13,
  },
  {
    name: "Erbiyum",
    symbol: "Er",
    atomicNumber: 68,
    atomicMass: 167.26,
    group: "3B",
    period: 6,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "9.07 g/cm³",
    meltingPoint: "1529 °C",
    boilingPoint: "2868 °C",
    electronConfiguration: "[Xe] 4f¹² 6s²",
    electronegativity: "1.24",
    ionizationEnergy: "589.3 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 14,
  },
  {
    name: "Tulyum",
    symbol: "Tm",
    atomicNumber: 69,
    atomicMass: 168.93,
    group: "3B",
    period: 6,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "9.32 g/cm³",
    meltingPoint: "1545 °C",
    boilingPoint: "1950 °C",
    electronConfiguration: "[Xe] 4f¹³ 6s²",
    electronegativity: "1.25",
    ionizationEnergy: "596.7 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 15,
  },
  {
    name: "İterbiyum",
    symbol: "Yb",
    atomicNumber: 70,
    atomicMass: 173.04,
    group: "3B",
    period: 6,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "6.90 g/cm³",
    meltingPoint: "824 °C",
    boilingPoint: "1196 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 6s²",
    electronegativity: "1.1",
    ionizationEnergy: "603.4 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 16,
  },
  {
    name: "Lutesyum",
    symbol: "Lu",
    atomicNumber: 71,
    atomicMass: 174.97,
    group: "3B",
    period: 6,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "9.84 g/cm³",
    meltingPoint: "1663 °C",
    boilingPoint: "3402 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹ 6s²",
    electronegativity: "1.27",
    ionizationEnergy: "523.5 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 17,
  },
  {
    name: "Hafniyum",
    symbol: "Hf",
    atomicNumber: 72,
    atomicMass: 178.49,
    group: "4B",
    period: 6,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "13.31 g/cm³",
    meltingPoint: "2233 °C",
    boilingPoint: "4603 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 5d² 6s²",
    electronegativity: "1.3",
    ionizationEnergy: "658.5 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 4,
  },
  {
    name: "Tantal",
    symbol: "Ta",
    atomicNumber: 73,
    atomicMass: 180.95,
    group: "5B",
    period: 6,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "16.65 g/cm³",
    meltingPoint: "3017 °C",
    boilingPoint: "5458 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 5d³ 6s²",
    electronegativity: "1.5",
    ionizationEnergy: "761 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 5,
  },
  {
    name: "Tungsten",
    symbol: "W",
    atomicNumber: 74,
    atomicMass: 183.84,
    group: "6B",
    period: 6,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "19.25 g/cm³",
    meltingPoint: "3422 °C",
    boilingPoint: "5555 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁴ 6s²",
    electronegativity: "2.36",
    ionizationEnergy: "770 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 6,
  },
  {
    name: "Renyum",
    symbol: "Re",
    atomicNumber: 75,
    atomicMass: 186.21,
    group: "7B",
    period: 6,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "21.02 g/cm³",
    meltingPoint: "3186 °C",
    boilingPoint: "5596 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁵ 6s²",
    electronegativity: "1.9",
    ionizationEnergy: "760 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 7,
  },
  {
    name: "Osmiyum",
    symbol: "Os",
    atomicNumber: 76,
    atomicMass: 190.23,
    group: "8B",
    period: 6,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "22.59 g/cm³",
    meltingPoint: "3033 °C",
    boilingPoint: "5012 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁶ 6s²",
    electronegativity: "2.2",
    ionizationEnergy: "840 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 8,
  },
  {
    name: "İridyum",
    symbol: "Ir",
    atomicNumber: 77,
    atomicMass: 192.22,
    group: "8B",
    period: 6,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "22.56 g/cm³",
    meltingPoint: "2446 °C",
    boilingPoint: "4428 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁷ 6s²",
    electronegativity: "2.2",
    ionizationEnergy: "880 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 9,
  },
  {
    name: "Platin",
    symbol: "Pt",
    atomicNumber: 78,
    atomicMass: 195.08,
    group: "8B",
    period: 6,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "21.45 g/cm³",
    meltingPoint: "1768.3 °C",
    boilingPoint: "3825 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    electronegativity: "2.28",
    ionizationEnergy: "870 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 10,
  },
  {
    name: "Altın",
    symbol: "Au",
    atomicNumber: 79,
    atomicMass: 196.97,
    group: "1B",
    period: 6,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Altın",
    density: "19.32 g/cm³",
    meltingPoint: "1064.18 °C",
    boilingPoint: "2856 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    electronegativity: "2.54",
    ionizationEnergy: "890.1 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 11,
  },
  {
    name: "Cıva",
    symbol: "Hg",
    atomicNumber: 80,
    atomicMass: 200.59,
    group: "2B",
    period: 6,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Sıvı",
    color: "Gümüş",
    density: "13.534 g/cm³",
    meltingPoint: "-38.83 °C",
    boilingPoint: "356.73 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    electronegativity: "2.00",
    ionizationEnergy: "1007.1 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 12,
  },
  {
    name: "Talyum",
    symbol: "Tl",
    atomicNumber: 81,
    atomicMass: 204.38,
    group: "3A",
    period: 6,
    block: "p",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "11.85 g/cm³",
    meltingPoint: "304 °C",
    boilingPoint: "1473 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    electronegativity: "1.62",
    ionizationEnergy: "589.4 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 13,
  },
  {
    name: "Kurşun",
    symbol: "Pb",
    atomicNumber: 82,
    atomicMass: 207.2,
    group: "4A",
    period: 6,
    block: "p",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gri",
    density: "11.34 g/cm³",
    meltingPoint: "327.46 °C",
    boilingPoint: "1749 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    electronegativity: "2.33",
    ionizationEnergy: "715.6 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 14,
  },
  {
    name: "Bizmut",
    symbol: "Bi",
    atomicNumber: 83,
    atomicMass: 208.98,
    group: "5A",
    period: 6,
    block: "p",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "9.78 g/cm³",
    meltingPoint: "271.3 °C",
    boilingPoint: "1564 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    electronegativity: "2.02",
    ionizationEnergy: "703 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 15,
  },
  {
    name: "Polonyum",
    symbol: "Po",
    atomicNumber: 84,
    atomicMass: 209,
    group: "6A",
    period: 6,
    block: "p",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "9.32 g/cm³",
    meltingPoint: "254 °C",
    boilingPoint: "962 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    electronegativity: "2.0",
    ionizationEnergy: "812.1 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 16,
  },
  {
    name: "Astatin",
    symbol: "At",
    atomicNumber: 85,
    atomicMass: 210,
    group: "7A",
    period: 6,
    block: "p",
    metalNonmetal: "Yarı metal",
    phase: "Katı",
    color: "Metalik",
    density: "7 g/cm³",
    meltingPoint: "302 °C",
    boilingPoint: "337 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    electronegativity: "2.2",
    ionizationEnergy: "890 kJ/mol",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 17,
  },
  {
    name: "Radon",
    symbol: "Rn",
    atomicNumber: 86,
    atomicMass: 222,
    group: "8A",
    period: 6,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Gaz",
    color: "Renksiz",
    density: "9.73 g/L",
    meltingPoint: "-71 °C",
    boilingPoint: "-61.7 °C",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    electronegativity: "Yok (soygaz olduğu için)",
    ionizationEnergy: "1037 kJ/mol",
    bonding: "Kimyasal bağ yapmaz.",
    position: 18,
  },
  {
    name: "Fransiyum",
    symbol: "Fr",
    atomicNumber: 87,
    atomicMass: 223,
    group: "1A",
    period: 7,
    block: "s",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Metalik",
    density: "1.87 g/cm³",
    meltingPoint: "27 °C",
    boilingPoint: "677 °C",
    electronConfiguration: "[Rn] 7s¹",
    electronegativity: "0.7",
    ionizationEnergy: "380 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 1,
  },
  {
    name: "Radyum",
    symbol: "Ra",
    atomicNumber: 88,
    atomicMass: 226,
    group: "2A",
    period: 7,
    block: "s",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "5.5 g/cm³",
    meltingPoint: "700 °C",
    boilingPoint: "1737 °C",
    electronConfiguration: "[Rn] 7s²",
    electronegativity: "0.9",
    ionizationEnergy: "509.3 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 2,
  },
  {
    name: "Aktinyum",
    symbol: "Ac",
    atomicNumber: 89,
    atomicMass: 227,
    group: "3B",
    period: 7,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "10.07 g/cm³",
    meltingPoint: "1050 °C",
    boilingPoint: "3200 °C",
    electronConfiguration: "[Rn] 6d¹ 7s²",
    electronegativity: "1.1",
    ionizationEnergy: "499 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 3,
  },
  {
    name: "Toryum",
    symbol: "Th",
    atomicNumber: 90,
    atomicMass: 232.04,
    group: "3B",
    period: 7,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "11.72 g/cm³",
    meltingPoint: "1750 °C",
    boilingPoint: "4788 °C",
    electronConfiguration: "[Rn] 6d² 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "587 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 4,
  },
  {
    name: "Protaktinyum",
    symbol: "Pa",
    atomicNumber: 91,
    atomicMass: 231.04,
    group: "3B",
    period: 7,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "15.37 g/cm³",
    meltingPoint: "1572 °C",
    boilingPoint: "4000 °C",
    electronConfiguration: "[Rn] 5f² 6d¹ 7s²",
    electronegativity: "1.5",
    ionizationEnergy: "568 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 5,
  },
  {
    name: "Uranyum",
    symbol: "U",
    atomicNumber: 92,
    atomicMass: 238.03,
    group: "3B",
    period: 7,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "18.95 g/cm³",
    meltingPoint: "1132.2 °C",
    boilingPoint: "4131 °C",
    electronConfiguration: "[Rn] 5f³ 6d¹ 7s²",
    electronegativity: "1.38",
    ionizationEnergy: "597.6 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 6,
  },
  {
    name: "Neptünyum",
    symbol: "Np",
    atomicNumber: 93,
    atomicMass: 237,
    group: "3B",
    period: 7,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "20.45 g/cm³",
    meltingPoint: "644 °C",
    boilingPoint: "3902 °C",
    electronConfiguration: "[Rn] 5f⁴ 6d¹ 7s²",
    electronegativity: "1.36",
    ionizationEnergy: "604.5 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 7,
  },
  {
    name: "Plütonyum",
    symbol: "Pu",
    atomicNumber: 94,
    atomicMass: 244,
    group: "3B",
    period: 7,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "19.84 g/cm³",
    meltingPoint: "640 °C",
    boilingPoint: "3228 °C",
    electronConfiguration: "[Rn] 5f⁶ 7s²",
    electronegativity: "1.28",
    ionizationEnergy: "584.7 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 8,
  },
  {
    name: "Amerikyum",
    symbol: "Am",
    atomicNumber: 95,
    atomicMass: 243,
    group: "3B",
    period: 7,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "13.69 g/cm³",
    meltingPoint: "1176 °C",
    boilingPoint: "2607 °C",
    electronConfiguration: "[Rn] 5f⁷ 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "578 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 9,
  },
  {
    name: "Küriyum",
    symbol: "Cm",
    atomicNumber: 96,
    atomicMass: 247,
    group: "3B",
    period: 7,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "13.51 g/cm³",
    meltingPoint: "1340 °C",
    boilingPoint: "3110 °C",
    electronConfiguration: "[Rn] 5f⁷ 6d¹ 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "581 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 10,
  },
  {
    name: "Berkelyum",
    symbol: "Bk",
    atomicNumber: 97,
    atomicMass: 247,
    group: "3B",
    period: 7,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "14.78 g/cm³",
    meltingPoint: "986 °C",
    boilingPoint: "2627 °C",
    electronConfiguration: "[Rn] 5f⁹ 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "601 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 11,
  },
  {
    name: "Kaliforniyum",
    symbol: "Cf",
    atomicNumber: 98,
    atomicMass: 251,
    group: "3B",
    period: 7,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "15.1 g/cm³",
    meltingPoint: "900 °C",
    boilingPoint: "1472 °C",
    electronConfiguration: "[Rn] 5f¹⁰ 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "608 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 12,
  },
  {
    name: "Einsteinyum",
    symbol: "Es",
    atomicNumber: 99,
    atomicMass: 252,
    group: "3B",
    period: 7,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "8.84 g/cm³",
    meltingPoint: "860 °C",
    boilingPoint: "996 °C",
    electronConfiguration: "[Rn] 5f¹¹ 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "619 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 13,
  },
  {
    name: "Fermiyum",
    symbol: "Fm",
    atomicNumber: 100,
    atomicMass: 257,
    group: "3B",
    period: 7,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "9.7 g/cm³",
    meltingPoint: "1527 °C",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹² 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "627 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 14,
  },
  {
    name: "Mendelevyum",
    symbol: "Md",
    atomicNumber: 101,
    atomicMass: 258,
    group: "3B",
    period: 7,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "10.3 g/cm³",
    meltingPoint: "827 °C",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹³ 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "635 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 15,
  },
  {
    name: "Nobelyum",
    symbol: "No",
    atomicNumber: 102,
    atomicMass: 259,
    group: "3B",
    period: 7,
    block: "f",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "9.9 g/cm³",
    meltingPoint: "827 °C",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "642 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 16,
  },
  {
    name: "Lawrensiyum",
    symbol: "Lr",
    atomicNumber: 103,
    atomicMass: 262,
    group: "3B",
    period: 7,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Gümüş",
    density: "15.6 g/cm³",
    meltingPoint: "1627 °C",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 7s² 7p¹",
    electronegativity: "1.3",
    ionizationEnergy: "470 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 17,
  },
  {
    name: "Rutherfordiyum",
    symbol: "Rf",
    atomicNumber: 104,
    atomicMass: 267,
    group: "4B",
    period: 7,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Unknown",
    density: "23 g/cm³",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 6d² 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "580 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 4,
  },
  {
    name: "Dubniyum",
    symbol: "Db",
    atomicNumber: 105,
    atomicMass: 270,
    group: "5B",
    period: 7,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Unknown",
    density: "29.3 g/cm³",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 6d³ 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "664 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 5,
  },
  {
    name: "Seaborgiyum",
    symbol: "Sg",
    atomicNumber: 106,
    atomicMass: 271,
    group: "6B",
    period: 7,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Unknown",
    density: "35 g/cm³",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁴ 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "742 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 6,
  },
  {
    name: "Bohriyum",
    symbol: "Bh",
    atomicNumber: 107,
    atomicMass: 270,
    group: "7B",
    period: 7,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Unknown",
    density: "37.1 g/cm³",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁵ 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "742 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 7,
  },
  {
    name: "Hassiyum",
    symbol: "Hs",
    atomicNumber: 108,
    atomicMass: 277,
    group: "8B",
    period: 7,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Unknown",
    density: "40.7 g/cm³",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁶ 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "730 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 8,
  },
  {
    name: "Meitneriyum",
    symbol: "Mt",
    atomicNumber: 109,
    atomicMass: 278,
    group: "8B",
    period: 7,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Unknown",
    density: "37.4 g/cm³",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁷ 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "800 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 9,
  },
  {
    name: "Darmstadtiyum",
    symbol: "Ds",
    atomicNumber: 110,
    atomicMass: 281,
    group: "8B",
    period: 7,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Unknown",
    density: "34.8 g/cm³",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁸ 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "800 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 10,
  },
  {
    name: "Röntgeniyum",
    symbol: "Rg",
    atomicNumber: 111,
    atomicMass: 282,
    group: "1B",
    period: 7,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Unknown",
    density: "28.7 g/cm³",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s¹",
    electronegativity: "1.3",
    ionizationEnergy: "1020 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 11,
  },
  {
    name: "Kopernikyum",
    symbol: "Cn",
    atomicNumber: 112,
    atomicMass: 285,
    group: "2B",
    period: 7,
    block: "d",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Unknown",
    density: "23.7 g/cm³",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    electronegativity: "1.3",
    ionizationEnergy: "1150 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 12,
  },
  {
    name: "Nihonyum",
    symbol: "Nh",
    atomicNumber: 113,
    atomicMass: 286,
    group: "3A",
    period: 7,
    block: "p",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Unknown",
    density: "16 g/cm³",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    electronegativity: "1.3",
    ionizationEnergy: "1130 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 13,
  },
  {
    name: "Flerovyum",
    symbol: "Fl",
    atomicNumber: 114,
    atomicMass: 289,
    group: "4A",
    period: 7,
    block: "p",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Unknown",
    density: "14 g/cm³",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    electronegativity: "1.3",
    ionizationEnergy: "1130 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 14,
  },
  {
    name: "Moskavyum",
    symbol: "Mc",
    atomicNumber: 115,
    atomicMass: 290,
    group: "5A",
    period: 7,
    block: "p",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Unknown",
    density: "13.5 g/cm³",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    electronegativity: "1.3",
    ionizationEnergy: "1130 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 15,
  },
  {
    name: "Livermoryum",
    symbol: "Lv",
    atomicNumber: 116,
    atomicMass: 293,
    group: "6A",
    period: 7,
    block: "p",
    metalNonmetal: "Metal",
    phase: "Katı",
    color: "Unknown",
    density: "12.9 g/cm³",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    electronegativity: "1.3",
    ionizationEnergy: "1130 kJ/mol",
    bonding: "Genellikle iyonik bağ yapar.",
    position: 16,
  },
  {
    name: "Tenesin",
    symbol: "Ts",
    atomicNumber: 117,
    atomicMass: 294,
    group: "7A",
    period: 7,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Katı",
    color: "Unknown",
    density: "Unknown",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    electronegativity: "Unknown",
    ionizationEnergy: "Unknown",
    bonding: "Genellikle kovalent bağ yapar.",
    position: 17,
  },
  {
    name: "Oganesson",
    symbol: "Og",
    atomicNumber: 118,
    atomicMass: 294,
    group: "8A",
    period: 7,
    block: "p",
    metalNonmetal: "Ametal",
    phase: "Gaz",
    color: "Unknown",
    density: "Unknown",
    meltingPoint: "Unknown",
    boilingPoint: "Unknown",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    electronegativity: "Unknown",
    ionizationEnergy: "Unknown",
    bonding: "Kimyasal bağ yapmaz.",
    position: 18,
  },
];
